name: chisel
summary: Chisel is a software tool for carving and cutting Debian packages!
description: |
  Chisel can derive a minimal Ubuntu-like Linux distribution
  using a release database that defines "slices" of existing packages.
  Slices enable developers to cherry-pick just the files they need
  from the Ubuntu archives, and combine them to create a new
  filesystem which can be packaged into an OCI-compliant
  container image or similar.

  This snap can only install the slices in a location inside the
  user $HOME directory i.e. the --root option in "cut" command
  should have a location inside the user $HOME directory.
issues:
  - https://github.com/canonical/chisel/issues
  - https://github.com/Canonical/chisel/security/advisories
source-code: https://github.com/canonical/chisel
license: AGPL-3.0
adopt-info: chisel-release-data
contact:
  - rocks@canonical.com
  - security@ubuntu.com

base: core22
confinement: strict

parts:
  chisel:
    plugin: go
    source: .
    build-snaps:
      - go/1.22/stable
    build-environment:
      - CGO_ENABLED: 0
      - GOFLAGS: -trimpath -ldflags=-w -ldflags=-s
    override-build: |
      go generate ./cmd
      craftctl default
    stage:
      - -bin/chrorder

  chisel-release-data:
    plugin: nil
    source: .
    override-build: |
      # set snap version
      version="$(${CRAFT_STAGE}/bin/chisel version)"
      craftctl set version="$version"

      # chisel releases are semantically versioned and
      # have a "v" prefix
      [[ "${version}" == *"git"* ]] && grade=devel || grade=stable
      craftctl set grade="$grade"
    after: [chisel]

plugs:
  etc-apt-auth-conf-d:
    interface: system-files
    read:
      - /etc/apt/auth.conf.d
      - /etc/apt/auth.conf.d/90ubuntu-advantage

apps:
  chisel:
    command: bin/chisel
    plugs:
      - network
      - home
      - etc-apt-auth-conf-d
