name: Build

on:
  workflow_dispatch:
  push:
    tags: [v*]
    branches: [main]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [main]
  release:
    types: [published]

jobs:
  build-chisel:
    name: Build Chisel
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: 'amd64'
            machine_arch: 'X86-64'
          - arch: 'arm'
            machine_arch: 'ARM'
          - arch: 'arm64'
            machine_arch: 'AArch64'
          - arch: 'ppc64le'
            machine_arch: 'PowerPC64'
          - arch: 'riscv64'
            machine_arch: 'RISC-V'
          - arch: 's390x'
            machine_arch: 'S/390'
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      # The checkout action in previous step overwrites annonated tag
      # with lightweight tags breaking ``git describe``
      # See https://github.com/actions/checkout/issues/882
      # and https://github.com/actions/checkout/issues/290
      # The following step is a workaround to restore the latest tag
      # to it's original state.
      - name: Restore (annonated) tag
        run: git fetch --force origin ${GITHUB_REF}:${GITHUB_REF}
        if: ${{ github.ref_type == 'tag' }}

      - uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version-file: 'go.mod'

      - name: Build Chisel for linux/${{ matrix.arch }}
        id: build
        env:
          GOOS: "linux"
          GOARCH: ${{ matrix.arch }}
          CGO_ENABLED: "0"
        run: |
          echo "Generating version file"
          go generate ./cmd/

          echo "Building for $GOOS $GOARCH"
          go build -trimpath -ldflags='-s -w' ./cmd/chisel

          # Get version via "chisel version" to ensure it matches that exactly
          CHISEL_VERSION=$(GOOS=linux GOARCH=amd64 go run ./cmd/chisel version)
          echo "Version: $CHISEL_VERSION"

          # Version should not be "unknown"
          [ "$CHISEL_VERSION" != "unknown" ] || exit 1

          # Share variables with subsequent steps
          echo "CHISEL_VERSION=${CHISEL_VERSION}" >>$GITHUB_OUTPUT

      - name: Test if is executable
        run: test -x ./chisel

      - name: Test if binary has the right machine architecture
        run: |
          [ "$(readelf -h chisel | grep 'Machine:' | awk -F' ' '{print $NF}')" == "${{ matrix.machine_arch }}" ]

      - name: Create archive
        id: archive
        env:
          GOOS: "linux"
          GOARCH: ${{ matrix.arch }}
          CHISEL_VERSION: ${{ steps.build.outputs.CHISEL_VERSION }}
        run: |
          ARCHIVE_FILE=chisel_${CHISEL_VERSION}_${GOOS}_${GOARCH}.tar.gz
          ARCHIVE_FILE_SHA384="${ARCHIVE_FILE}.sha384"
          echo "Creating archive $ARCHIVE_FILE"

          mkdir -p dist/
          cp chisel LICENSE README.md dist/
          find dist -printf "%P\n" | tar -czf $ARCHIVE_FILE --no-recursion -C dist -T -
          sha384sum "${ARCHIVE_FILE}" > "${ARCHIVE_FILE_SHA384}"

          # Share variables with subsequent steps
          echo "ARCHIVE_FILE=${ARCHIVE_FILE}" >>$GITHUB_OUTPUT
          echo "ARCHIVE_FILE_SHA384=${ARCHIVE_FILE_SHA384}" >>$GITHUB_OUTPUT

      - name: Upload archive as Actions artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: ${{ steps.archive.outputs.ARCHIVE_FILE }}
          path: |
            ${{ steps.archive.outputs.ARCHIVE_FILE }}
            ${{ steps.archive.outputs.ARCHIVE_FILE_SHA384 }}

      - name: Upload archive to release
        env:
          CHISEL_VERSION: ${{ steps.build.outputs.CHISEL_VERSION }}
          ARCHIVE_FILE: ${{ steps.archive.outputs.ARCHIVE_FILE }}
          ARCHIVE_FILE_SHA384: ${{ steps.archive.outputs.ARCHIVE_FILE_SHA384 }}
          # If triggered by a "release" event, this additional and final step
          # of the job will upload the Chisel binaries (and checksums) to the corresponding
          # GitHub release. This operation NEEDS "contents: write" permissions.
          # Security concerns:
          #  - Why a custom token instead of GITHUB_TOKEN?
          #    - The GITHUB_TOKEN only has "readonly" permissions by default.
          #  - Why not add "permissions: {contents:write}" to this workflow [1]?
          #    - While this would elevate the GITHUB_TOKEN permissions to what we require, it
          #      would do it for the entire job (ALL steps), which increases the attack surface unnecessarily.
          #  - Why is it safer to use the ROCKSBOT_CHISEL_CONTENTS token?
          #    1. it is limited to this step of the workflow (unlike GITHUB_TOKEN, which is always available)
          #    2. this particular step only runs when the "event == release"
          #    3. the step's script doesn't rely on 3rd party actions
          #    4. the current workflow triggers are all maintainer-driven, except for "pull_request",
          #       but the latter is designed not to use any secrets during execution from fork-based PRs
          #        - NOTE: in fact, custom secrets are never passed to fork-based PR workflows, unlike GITHUB_TOKEN
          #          which is available with "readonly" permissions [2]
          # - How could this token be compromised?
          #   - By unintentionally merging a change that allows this step to run unvetted scripts
          #     (either via a "pull_request_target", use of an insecure 3rd party action, or malicious changes to the
          #     current script)
          # [1] https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax#permissions
          # [2] https://docs.github.com/en/actions/reference/workflows-and-actions/events-that-trigger-workflows#workflows-in-forked-repositories
          GITHUB_TOKEN: ${{ secrets.ROCKSBOT_CHISEL_CONTENTS }}
        if: ${{ github.event_name == 'release' }}
        run: |
          echo "Uploading $ARCHIVE_FILE to release $CHISEL_VERSION"
          gh release upload $CHISEL_VERSION $ARCHIVE_FILE
          gh release upload $CHISEL_VERSION $ARCHIVE_FILE_SHA384
