name: License check

on:
  workflow_dispatch:
  push:
  pull_request:
    branches: [main]

jobs:
  external-packages:
    runs-on: ubuntu-22.04
    name: External packages license check
    steps:
      - uses: actions/checkout@v3

      - name: Run license check
        run: |
          ./github/scripts/external-packages-license-check.sh
