name: Security

on:
  schedule:
    - cron: "0 1 * * *"

jobs:
  scan:
    name: Scan for known vulnerabilities
    runs-on: ubuntu-latest
    env:
      TRIVY_RESULTS: 'trivy-results.sarif'
    steps:
      - name: Get latest release download URL
        id: release
        run: |
          url=$(gh release view --json assets --jq \
            '.assets[] | select(.name | test("linux_amd64.tar.gz$")) | .url' \
            --repo ${{ github.repository }})
          echo "url=$url" >> "$GITHUB_OUTPUT"
        env:
          # TODO: replace with fine grained token once created.
          GH_TOKEN: ${{ github.token }}

      - name: Download and extract latest release
        run: |
          mkdir release-scan
          curl -sSL "${{ steps.release.outputs.url }}" | tar -xz -C release-scan

      - name: Run Trivy vulnerability scanner in on release
        uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1
        with:
          scan-type: 'rootfs'
          scan-ref: './release-scan/chisel'
          format: 'sarif'
          output: ${{ env.TRIVY_RESULTS }}
          # TODO: Replace with the fine grained token once created.
          github-pat: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ env.TRIVY_RESULTS }}

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.TRIVY_RESULTS }}
          path: ${{ env.TRIVY_RESULTS }}

      - name: Raise error on HIGH,CRITICAL vulnerabilities
        uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1
        with:
          scan-type: 'rootfs'
          scan-ref: './release-scan/chisel'
          severity: 'CRITICAL,HIGH'
          exit-code: '1'
          # TODO: Replace with the fine grained token once created.
          github-pat: ${{ secrets.GITHUB_TOKEN }}
