name: Security

on:
  schedule:
    - cron: "0 1 * * *"

jobs:
  scan:
    name: Scan for known vulnerabilities
    runs-on: ubuntu-latest
    env:
      TRIVY_RESULTS: 'trivy-results.sarif'
    steps:
      - uses: actions/checkout@v3

      - name: Run Trivy vulnerability scanner in fs mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: ${{ env.TRIVY_RESULTS }}

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ env.TRIVY_RESULTS }}

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.TRIVY_RESULTS }}
          path: ${{ env.TRIVY_RESULTS }}

      - name: Raise error on HIGH,CRITICAL vulnerabilities
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          severity: 'CRITICAL,HIGH'
          exit-code: '1'
